# Generated by Django 4.0.6 on 2022-07-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_name', models.TextField()),
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_floor', models.IntegerField(null=True)),
                ('min_floor', models.IntegerField(null=True)),
                ('context', models.CharField(max_length=1024)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='listapp.company')),
            ],
            options={
                'ordering': ['-max_floor'],
            },
        ),
    ]
