# Generated by Django 4.0.6 on 2022-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
