# Generated by Django 4.0.5 on 2022-07-24 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
                ('is_admin', models.IntegerField(default='0')),
                ('name', models.CharField(default='', max_length=45)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('drawing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drawing', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'drawing',
            },
        ),
        migrations.CreateModel(
            name='glass',
            fields=[
                ('glass_id', models.AutoField(primary_key=True, serialize=False)),
                ('glass_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'glass',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('raw_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(max_length=100, null=True)),
                ('voice', models.CharField(max_length=100, null=True)),
                ('voice_to_text', models.CharField(max_length=100, null=True)),
                ('upload_user_id', models.CharField(max_length=45, null=True)),
                ('upload_target_building', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'raw_data',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('drawing_id', models.ForeignKey(db_column='drawing_id', on_delete=django.db.models.deletion.CASCADE, to='home.drawing')),
            ],
            options={
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_name', models.TextField()),
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_floor', models.IntegerField(null=True)),
                ('min_floor', models.IntegerField(null=True)),
                ('context', models.CharField(max_length=1024)),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
            options={
                'db_table': 'building',
                'ordering': ['-max_floor'],
            },
        ),
    ]
