# Generated by Django 4.0.5 on 2022-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Info',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('category_L', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
