# Generated by Django 4.0.5 on 2022-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_item_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=20)),
            ],
        ),
    ]
