# Generated by Django 4.0.5 on 2022-07-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
