# Generated by Django 4.0.5 on 2022-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='glass',
            fields=[
                ('glass_id', models.AutoField(primary_key=True, serialize=False)),
                ('glass_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'glass',
            },
        ),
        migrations.CreateModel(
            name='raw_data',
            fields=[
                ('raw_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(max_length=100, null=True)),
                ('voice', models.CharField(max_length=100, null=True)),
                ('voice_to_text', models.CharField(max_length=100, null=True)),
                ('upload_user_id', models.CharField(max_length=45, null=True)),
                ('upload_target_building', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'raw_data',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
