# Generated by Django 4.0.5 on 2022-07-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_floor_building_id_issue_building_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_data',
            old_name='upload_target_building',
            new_name='upload_target_building_id',
        ),
    ]
