# Generated by Django 4.0.5 on 2022-07-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_alter_building_table_alter_company_table'),
        ('home', '0005_glass_raw_data_account_is_admin_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listapp.company'),
        ),
    ]
