# Generated by Django 4.0.5 on 2022-07-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_upload_target_building_raw_data_upload_target_building_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='building_id',
        ),
    ]
