# Generated by Django 4.0.5 on 2022-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_item_info 2'),
        ('home', '0006_rename_builing_context_building_building_context'),
        ('home', '0007_remove_issue_building_id'),
    ]

    operations = [
    ]
