# Generated by Django 4.0.5 on 2022-08-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_image_key_voice_to_text_remove_floor_drawing_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='key',
            table='key',
        ),
        migrations.AlterModelTable(
            name='voice_to_text',
            table='voice_to_text',
        ),
    ]
