# Generated by Django 4.0.5 on 2022-08-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_image_table_alter_key_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='key',
            table='keys',
        ),
    ]
