# Generated by Django 4.0.5 on 2022-08-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_item_info'),
        ('home', '0002_delete_item_info 3'),
        ('home', '0002_delete_item_info 4'),
        ('home', '0012_rename_key_key_table_alter_key_table_table'),
    ]

    operations = [
    ]
