# Generated by Django 4.0.5 on 2022-09-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_issue_raw_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_target_building_name',
            new_name='upload_target_building_id',
        ),
        migrations.RenameField(
            model_name='voice_to_text',
            old_name='upload_target_building_name',
            new_name='upload_target_building_id',
        ),
    ]
