# Generated by Django 4.0.5 on 2022-09-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_upload_target_building_name_image_upload_target_building_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='key',
            new_name='key_value',
        ),
        migrations.RenameField(
            model_name='key_table',
            old_name='key',
            new_name='key_value',
        ),
        migrations.RenameField(
            model_name='voice_to_text',
            old_name='key',
            new_name='key_value',
        ),
    ]
