# Generated by Django 3.2.5 on 2022-07-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('drawing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('drawing', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Drawing',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('drawing_id', models.ForeignKey(db_column='drawing_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.drawing')),
            ],
            options={
                'db_table': 'floor',
            },
        ),
    ]
